# Generated by Django 3.0 on 2023-11-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letting', '0004_remove_letting_address'),
        ('oc_letting_site', '0003_auto_20231119_1052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
