# Generated by Django 3.0 on 2023-11-19 11:49

from django.db import migrations

def transfer_address_data(apps, schema_editor):
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    NewAddress = apps.get_model('oc_letting_site', 'Address')
    for old_address in OldAddress.objects.all():
        NewAddress(
            id=old_address.id,
            number=old_address.number,
            street=old_address.street,
            city=old_address.city,
            state=old_address.state,
            zip_code=old_address.zip_code,
            country_iso_code=old_address.country_iso_code
        ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('oc_letting_site', '0003_auto_20231119_1052'),
    ]

    operations = [
        migrations.RunPython(transfer_address_data),
    ]
