# Generated by Django 3.0 on 2023-11-19 11:47

from django.db import migrations

def transfer_profile_data(apps, schema_editor):
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    NewProfile = apps.get_model('profiles', 'Profile')
    for old_profile in OldProfile.objects.all():
        NewProfile(
            id=old_profile.id,
            user=old_profile.user,
            favorite_city=old_profile.favorite_city
        ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20231119_1052'),
    ]

    operations = [
        migrations.RunPython(transfer_profile_data),
    ]
