version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: echo "Le processus de build commence"
      - run:
          name: Installation des Dépendances
          command: pip install -r requirements.txt
      - run:
          name: Exécution des Tests
          command: python manage.py test
      - setup_remote_docker
      - run:
          name: Construction de l'Image Docker
          command: docker build -t mickaelsalmon/oc_letting_site:latest .
      - run:
          name: Push de l'Image vers Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push mickaelsalmon/oc_letting_site:latest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
