version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.12
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SENTRY_DSN: ${SENTRY_DSN}
    steps:
      - checkout
      - run: echo "Le processus de build commence"
      - run:
          name: Print SENTRY_DSN
          command: echo $SENTRY_DSN
      - run:
          name: Installation des Dépendances
          command: |
            pip install -r requirements.txt
      - run:
          name: Collecte des Fichiers Statiques
          command: python manage.py collectstatic --noinput
      - run:
          name: Vérification du Linting avec Flake8
          command: flake8 .
      - run:
          name: Exécution des Tests et rapport de couverture
          command: |
            coverage run -m pytest tests/*.*
            coverage report
      - run:
          name: Test de Gunicorn
          command: |
            gunicorn --check-config oc_letting_site.wsgi:application
      - setup_remote_docker
      - run:
          name: Construction de l'Image Docker
          command: docker build -t mickaelsalmon/oc_letting_site:latest .
      - run:
          name: Push de l'Image vers Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push mickaelsalmon/oc_letting_site:latest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
