# Generated by Django 3.0 on 2023-11-19 11:47

from django.db import migrations

def transfer_letting_data(apps, schema_editor):
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')
    NewLetting = apps.get_model('letting', 'Letting')
    NewAddress = apps.get_model('oc_letting_site', 'Address')  # Ou 'letting', selon la configuration de ton modèle
    for old_letting in OldLetting.objects.all():
        try:
            new_address = NewAddress.objects.get(id=old_letting.address.id)
        except NewAddress.DoesNotExist:
            # Crée une nouvelle adresse en utilisant les champs de l'ancien modèle Address
            new_address = NewAddress.objects.create(
                number=old_letting.address.number,
                street=old_letting.address.street,
                city=old_letting.address.city,
                state=old_letting.address.state,
                zip_code=old_letting.address.zip_code,
                country_iso_code=old_letting.address.country_iso_code
            )

        # Créer une nouvelle instance de Letting avec la nouvelle adresse
        NewLetting.objects.create(
            title=old_letting.title,
            address=new_address
        )




class Migration(migrations.Migration):

    dependencies = [
        ('letting', '0003_auto_20231119_1052'),
    ]

    operations = [
        migrations.RunPython(transfer_letting_data),
    ]

