# Generated by Django 3.0 on 2023-11-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letting', '0003_auto_20231119_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letting',
            name='address',
        ),
    ]
